blank_issues_enabled: false
contact_links:
  - name: 💬 Questions & ideas
    url: https://github.com/Ali338991/Mole-Interface/discussions
    about: Ask questions or discuss ideas in GitHub Discussions.
